#!/bin/sh

if [[ $# -eq 1 ]]; then
    selected=$(pwd $1)
else
    selected=$(find ~/ ~/labs ~/dev ~/repos ~/test -mindepth 1 -maxdepth 1 -type d | fzf)
fi


if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if [[ -z $TMUX ]]; then
    tmux new-session -A -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
