foreground         #ECF1E4
background         #141414
cursor             #ECF1E4

active_tab_foreground     #1B1C1C
active_tab_background     #ECF1E4
inactive_tab_foreground   #ECF1E4
inactive_tab_background   #1B1C1C

active_border_color   #ECF1E4
inactive_border_color #1B1C1C
bell_border_color     #131515

color0      #131515
color1		#C0856E
color2		#96A286
color3		#8A7463
color4		#B29C7A
color5		#927748
color6		#96A286
color7		#DBE3D0
color8		#999F92
color9		#aeb1a9
color10		#1A1C1C
color11		#1A1C1C
color12		#574A3C
color13		#C29F60
color14		#C8D8B2
color15		#DBE3D0
